# -*- coding: utf-8 -*-
"""hanhaw_ex0907.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KyRt79sWT5iIqvowAo-cgSEzzKU1O_nk
"""

from typing import Annotated, Literal
from annotated_types import Gt
from pydantic import BaseModel

class Fruit(BaseModel):
  name: str
  color: Literal['red', 'green']
  weight: Annotated[float, Gt(0)]
  bazam: dict[str, list[tuple[int, bool, float]]]

print(
  Fruit(
      name='Apple',
      color='red',
      weight=4.2,
      bazam={'foobar': [(1, True, 0.1)]},
  )
)

